In [13]:
# <caption>Standard Types</caption>
# <tr><th>Mortar Type</th><th>28 day Compressive Strength</th><th>Mix Ratio</th><th>Water Retention</th><th>Bond Strength</th></tr>
text = """<table>
<tr><td style="text-align: center;":>M</td><td style="text-align: center;">2,500 psi</td><td style="text-align: center;">1/1/6</td><td style="text-align: center;">Low</td><td style="text-align: center;">High</td></tr>
<tr><td style="text-align: center;">S</td><td style="text-align: center;">1,800 psi</td><td style="text-align: center;">3/1/12</td><td style="text-align: center;">Medium</td><td style="text-align: center;">High</td></tr>
<tr><td style="text-align: center;">N</td><td style="text-align: center;">750 psi</td><td style="text-align: center;">2/1/9</td><td style="text-align: center;">High</td><td style="text-align: center;">Medium</td></tr>
<tr><td style="text-align: center;">O</td><td style="text-align: center;">350 psi</td><td style="text-align: center;">1/2/9</td><td style="text-align: center;">Very High</td><td style="text-align: center;">Low</td></tr>
<tr><td style="text-align: center;">K</td><td style="text-align: center;">75 psi</td><td style="text-align: center;">1/3/10</td><td style="text-align: center;">Very High</td><td style="text-align: center;">Very Low</td></tr>
</table>"""

In [19]:
from html.parser import HTMLParser
from recordclass import recordclass
Mortar_i = recordclass("Mortar_i","type strength mix retension bond_str")
mortars = []
Data = []
class MyHTMLParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.Data = []
    def handle_starttag(self, tag, attrs):
        pass
        #print("Encountered a start tag:", tag)
    def handle_endtag(self, tag):
        pass
        #print("Encountered an end tag :", tag)
    def handle_data(self, data):
        #print("Encountered some data  :", data)
        if data.strip() != '':
            self.Data.append(data)
        if len(self.Data)==5:
            mortars.append(Mortar_i(*self.Data))
            self.Data = []
        
parser = MyHTMLParser()
parser.feed(text)

In [20]:
mortars

[Mortar_i(type='M', strength='2,500 psi', mix='1/1/6', retension='Low', bond_str='High'),
 Mortar_i(type='S', strength='1,800 psi', mix='3/1/12', retension='Medium', bond_str='High'),
 Mortar_i(type='N', strength='750 psi', mix='2/1/9', retension='High', bond_str='Medium'),
 Mortar_i(type='O', strength='350 psi', mix='1/2/9', retension='Very High', bond_str='Low'),
 Mortar_i(type='K', strength='75 psi', mix='1/3/10', retension='Very High', bond_str='Very Low')]

In [36]:
Mortar = recordclass("Mortar_i","type strength mix retension bond_str bond_ext bond_dur leakage")
full_mortars = []
for mortar in mortars:
    M = mortar._asdict()
    if mortar.type == "M":
        M["bond_ext"] = "Low"
        M["bond_dur"] = "Very Low"
        M["leakage"] = "High"
    elif mortar.type == "S":
        M["bond_ext"] = "High"
        M["bond_dur"] = "Moderate"
        M["leakage"] = "Moderate"
    elif mortar.type == "N":
        M["bond_ext"] = "High"
        M["bond_dur"] = "High"
        M["leakage"] = "Low"
    elif mortar.type == "O":
        M["bond_ext"] = "Very High"
        M["bond_dur"] = "Very High"
        M["leakage"] = "Low"
    elif mortar.type == "K":
        M["bond_ext"] = "Very High"
        M["bond_dur"] = "Very High"
        M["leakage"] = "Low"
    m = Mortar(**M)
#     print(m)
    full_mortars.append(m)

In [42]:
text = """<table style="width:650px">
<caption>Standard Types</caption>
<tr><th>Mortar Type</th><th>28 day Compressive Strength</th>
<th>Mix Ratio</th><th>Water Retention</th>
<th>Bond Strength</th><th>Extent of Bond</th>
<th>Bond Durability</th><th>Permeability in Wall</th></tr>
"""
line_txt = "<tr><td>_1</td><td>_2</td><td>_3</td><td>_4</td><td>_5</td><td>_6</td><td>_7</td><td>_8</td></tr>"
num = ["_1","_2","_3","_4","_5","_6","_7","_8"]
for m in full_mortars:
    m_txt = line_txt
    for  a,b in zip(num,m._asdict().keys()):
        m_txt = m_txt.replace(a,m._asdict()[b])
    text+=m_txt+"\n"
text+="</table>"
print(text)
# text.

<table style="width:650px">
<caption>Standard Types</caption>
<tr><th>Mortar Type</th><th>28 day Compressive Strength</th>
<th>Mix Ratio</th><th>Water Retention</th>
<th>Bond Strength</th><th>Extent of Bond</th>
<th>Bond Durability</th><th>Permeability in Wall</th></tr>
<tr><td>M</td><td>2,500 psi</td><td>1/1/6</td><td>Low</td><td>High</td><td>Low</td><td>Very Low</td><td>High</td></tr>
<tr><td>S</td><td>1,800 psi</td><td>3/1/12</td><td>Medium</td><td>High</td><td>High</td><td>Moderate</td><td>Moderate</td></tr>
<tr><td>N</td><td>750 psi</td><td>2/1/9</td><td>High</td><td>Medium</td><td>High</td><td>High</td><td>Low</td></tr>
<tr><td>O</td><td>350 psi</td><td>1/2/9</td><td>Very High</td><td>Low</td><td>Very High</td><td>Very High</td><td>Low</td></tr>
<tr><td>K</td><td>75 psi</td><td>1/3/10</td><td>Very High</td><td>Very Low</td><td>Very High</td><td>Very High</td><td>Low</td></tr>
</table>


In [41]:
from IPython.display import HTML
HTML(text)

<table>
<caption>Standard Types</caption>
<tr>
<th rowspan="2">Mortar Type</th>
<th rowspan="2">28 day Compressive Strength</th>
<th rowspan="2">Mix Ratio</th>
<th rowspan="2">Water Retention</th>
<th rowspan="2">Bond Strength</th>
<th rowspan="2">Extent of Bond</th>
<th rowspan="2">Bond Durability</th>
<th rowspan="2">Permeability in Wall</th>
</tr>
<tr></tr>
<tr><td>M</td><td>2,500 psi</td><td>1/1/6</td><td>Low</td><td>High</td><td>Low</td><td>Very Low</td><td>High</td></tr>
<tr><td>S</td><td>1,800 psi</td><td>3/1/12</td><td>Medium</td><td>High</td><td>High</td><td>Moderate</td><td>Moderate</td></tr>
<tr><td>N</td><td>750 psi</td><td>2/1/9</td><td>High</td><td>Medium</td><td>High</td><td>High</td><td>Low</td></tr>
<tr><td>O</td><td>350 psi</td><td>1/2/9</td><td>Very High</td><td>Low</td><td>Very High</td><td>Very High</td><td>Low</td></tr>
<tr><td>K</td><td>75 psi</td><td>1/3/10</td><td>Very High</td><td>Very Low</td><td>Very High</td><td>Very High</td><td>Low</td></tr>
</table>

